//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplicationTestWCF.HelloWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnecdoteCnf", Namespace="http://schemas.datacontract.org/2004/07/Core.Anecdotes")]
    [System.SerializableAttribute()]
    public partial class AnecdoteCnf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VoteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fact {
            get {
                return this.FactField;
            }
            set {
                if ((object.ReferenceEquals(this.FactField, value) != true)) {
                    this.FactField = value;
                    this.RaisePropertyChanged("Fact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vote {
            get {
                return this.VoteField;
            }
            set {
                if ((this.VoteField.Equals(value) != true)) {
                    this.VoteField = value;
                    this.RaisePropertyChanged("Vote");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnecdoteDtc", Namespace="http://schemas.datacontract.org/2004/07/Core.Anecdotes")]
    [System.SerializableAttribute()]
    public partial class AnecdoteDtc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnecdoteVdm", Namespace="http://schemas.datacontract.org/2004/07/Core.Anecdotes")]
    [System.SerializableAttribute()]
    public partial class AnecdoteVdm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BienMeriteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JeValideField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplicationTestWCF.HelloWebService.CommentVdm[] ListCommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ParutionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BienMerite {
            get {
                return this.BienMeriteField;
            }
            set {
                if ((this.BienMeriteField.Equals(value) != true)) {
                    this.BienMeriteField = value;
                    this.RaisePropertyChanged("BienMerite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contenu {
            get {
                return this.ContenuField;
            }
            set {
                if ((object.ReferenceEquals(this.ContenuField, value) != true)) {
                    this.ContenuField = value;
                    this.RaisePropertyChanged("Contenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JeValide {
            get {
                return this.JeValideField;
            }
            set {
                if ((this.JeValideField.Equals(value) != true)) {
                    this.JeValideField = value;
                    this.RaisePropertyChanged("JeValide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplicationTestWCF.HelloWebService.CommentVdm[] ListComments {
            get {
                return this.ListCommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ListCommentsField, value) != true)) {
                    this.ListCommentsField = value;
                    this.RaisePropertyChanged("ListComments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Parution {
            get {
                return this.ParutionField;
            }
            set {
                if ((this.ParutionField.Equals(value) != true)) {
                    this.ParutionField = value;
                    this.RaisePropertyChanged("Parution");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentVdm", Namespace="http://schemas.datacontract.org/2004/07/Core.Comments")]
    [System.SerializableAttribute()]
    public partial class CommentVdm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloWebService.IServiceHello")]
    public interface IServiceHello {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHello/SayHello", ReplyAction="http://tempuri.org/IServiceHello/SayHelloResponse")]
        string SayHello(string who);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHello/Test", ReplyAction="http://tempuri.org/IServiceHello/TestResponse")]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHello/CNF_RetreiveAnecdote", ReplyAction="http://tempuri.org/IServiceHello/CNF_RetreiveAnecdoteResponse")]
        ConsoleApplicationTestWCF.HelloWebService.AnecdoteCnf[] CNF_RetreiveAnecdote(string tri, int nombreAnecdote, int pageNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHello/DTC_RetreiveAnecdote", ReplyAction="http://tempuri.org/IServiceHello/DTC_RetreiveAnecdoteResponse")]
        ConsoleApplicationTestWCF.HelloWebService.AnecdoteDtc[] DTC_RetreiveAnecdote(string tri, int pageNumber, string searchWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHello/VDM_NewAnecdote", ReplyAction="http://tempuri.org/IServiceHello/VDM_NewAnecdoteResponse")]
        void VDM_NewAnecdote(ConsoleApplicationTestWCF.HelloWebService.AnecdoteVdm ane);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHello/DTC_NewAnecdote", ReplyAction="http://tempuri.org/IServiceHello/DTC_NewAnecdoteResponse")]
        void DTC_NewAnecdote(ConsoleApplicationTestWCF.HelloWebService.AnecdoteDtc ane);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHello/CNF_NewAnecdote", ReplyAction="http://tempuri.org/IServiceHello/CNF_NewAnecdoteResponse")]
        void CNF_NewAnecdote(ConsoleApplicationTestWCF.HelloWebService.AnecdoteCnf ane);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceHelloChannel : ConsoleApplicationTestWCF.HelloWebService.IServiceHello, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHelloClient : System.ServiceModel.ClientBase<ConsoleApplicationTestWCF.HelloWebService.IServiceHello>, ConsoleApplicationTestWCF.HelloWebService.IServiceHello {
        
        public ServiceHelloClient() {
        }
        
        public ServiceHelloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHelloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHelloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHelloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello(string who) {
            return base.Channel.SayHello(who);
        }
        
        public string Test() {
            return base.Channel.Test();
        }
        
        public ConsoleApplicationTestWCF.HelloWebService.AnecdoteCnf[] CNF_RetreiveAnecdote(string tri, int nombreAnecdote, int pageNumber) {
            return base.Channel.CNF_RetreiveAnecdote(tri, nombreAnecdote, pageNumber);
        }
        
        public ConsoleApplicationTestWCF.HelloWebService.AnecdoteDtc[] DTC_RetreiveAnecdote(string tri, int pageNumber, string searchWord) {
            return base.Channel.DTC_RetreiveAnecdote(tri, pageNumber, searchWord);
        }
        
        public void VDM_NewAnecdote(ConsoleApplicationTestWCF.HelloWebService.AnecdoteVdm ane) {
            base.Channel.VDM_NewAnecdote(ane);
        }
        
        public void DTC_NewAnecdote(ConsoleApplicationTestWCF.HelloWebService.AnecdoteDtc ane) {
            base.Channel.DTC_NewAnecdote(ane);
        }
        
        public void CNF_NewAnecdote(ConsoleApplicationTestWCF.HelloWebService.AnecdoteCnf ane) {
            base.Channel.CNF_NewAnecdote(ane);
        }
    }
}
